name: Hiun Kim

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true

highlighter: rouge
future: true

author:
  name: Hiun Kim
  email: example@example.com

plugins:
  - jekyll-feed

permalink: /:year/:month/:day/:title.html
